# Generated by Django 3.2.7 on 2021-10-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crud_database',
            name='datatime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
